name: Rclone Copy
on:
  workflow_dispatch:
    inputs:
      fin:
        description: "File/Folder Name"
        required: false 

defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Installing Rclone
        run: |
          mkdir te 
          cd te && curl https://rclone.org/install.sh | sudo bash
      - name: Getting rclone config
        run: |
          cd ../../.. && cd .config/ && mkdir rclone && cd rclone && wget ${{ secrets.CON_URL }}

      - name: Copying
        run: |
          rclone copy "docsos;1/Kndmally" "docircc:kanmally" --no-traverse --progress 
